version: "3.8"

services:
  mysql:
    image: mysql:8.3
    container_name: movieapp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moviedb
      MYSQL_USER: movieuser
      MYSQL_PASSWORD: moviepass
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
